Repository spring-projects/spring-ai, pull requests merged in 2024-11, with the labels that each got.

#1641 Update property precedence in documentation
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/qianfan-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/minimax-embeddings.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/mistralai-embeddings.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/qianfan-embeddings.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/zhipuai-embeddings.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/image/qianfan-image.adoc
Labels: documentation

#1648 modify a document
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/testing.adoc
Labels: documentation

#1688 Add spring-ai-coherence-store to bom
  spring-ai-bom/pom.xml
Labels: coherence

#1699 fix: Improve error resilience of the Bedrock stream handling
  models/spring-ai-bedrock-converse/src/main/java/org/springframework/ai/bedrock/converse/BedrockProxyChatModel.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/api/AbstractBedrockApi.java
  models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/cohere/BedrockCohereChatModelIT.java
  models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/cohere/api/CohereChatBedrockApiIT.java
  models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/jurassic2/BedrockAi21Jurassic2ChatModelIT.java
  spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/converse/BedrockConverseProxyChatAutoConfiguration.java
Labels: bug, Bedrock, streaming, configuration

#1742 Add support for `@Component` to TypeResolverHelper
  spring-ai-core/src/main/java/org/springframework/ai/model/function/TypeResolverHelper.java
  spring-ai-core/src/test/java/org/springframework/ai/model/function/TypeResolverHelperIT.java
  spring-ai-core/src/test/java/org/springframework/ai/model/function/component/ComponentWeatherFunction.java
Labels: function calling

#1750 Update getting-started.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc
Labels: documentation

#1748 Update `Message.java` reference
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Labels: documentation

#1777 fix(bedrock-converse): Update tool use handling and add usage
  models/spring-ai-bedrock-converse/src/main/java/org/springframework/ai/bedrock/converse/BedrockProxyChatModel.java
  models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/BedrockConverseChatClientIT.java
  models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/BedrockConverseUsageAggregationTests.java
  models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/experiments/BedrockConverseChatModelMain.java
  models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/experiments/BedrockConverseChatModelMain2.java
  models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/experiments/BedrockConverseChatModelMain3.java
  spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallingOptionsBuilder.java
Labels: testing, Observability, Bedrock, aws

#1835 Portable ChatOptions ignored by OpenAiChatModel
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelIT.java
Labels: bug, chat options
