Repository spring-projects/spring-ai, pull requests merged in 2024-10, with the labels that each got.

#1445 Fix chroma property in IT
  spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/chroma/ChromaContainerConnectionDetailsFactoryTest.java
  spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/chroma/ChromaWithToken2ContainerConnectionDetailsFactoryTest.java
  spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/chroma/ChromaWithTokenContainerConnectionDetailsFactoryTest.java
Labels: testing

#1474 Update Observability documentation
  spring-ai-docs/src/main/antora/modules/ROOT/pages/observabilty/index.adoc
Labels: Observability

#1491 Extend observation support to Azure OpenAI models
  models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatModel.java
  models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiEmbeddingModel.java
  models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureOpenAiEmbeddingModelObservationIT.java
  spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/azure/openai/AzureOpenAiAutoConfiguration.java
Labels: azure, Observability

#1505 Enhance SafeGuardAdvisor with customizable failure response
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/SafeGuardAdvisor.java
Labels: bug, advisors

#1551 Ollama: add model auto-pull feature
  models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaChatModel.java
  models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaEmbeddingModel.java
  models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaModelPuller.java
  models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaOptions.java
  models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/BaseOllamaIT.java
  models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaChatModelIT.java
  models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaEmbeddingModelIT.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/ollama-embeddings.adoc
Labels: documentation, embedding, ollama, chat client, chat options

#1616 GH-513 fix: Support custom field names for Milvus VectorStore collection
  spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreAutoConfiguration.java
  spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreProperties.java
  spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreAutoConfigurationIT.java
  vector-stores/spring-ai-milvus-store/src/main/java/org/springframework/ai/vectorstore/MilvusVectorStore.java
  vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java
Labels: milvus

#1618 Fix example codes in docs
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/etl-pipeline.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/imageclient.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/testing.adoc
Labels: documentation
