Repository spring-projects/spring-ai, pull requests merged in 2024-08, with the labels that each got.

#1203 Streamline ChatOptions
  models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/AnthropicChatOptions.java
  models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatOptions.java
  models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiEmbeddingOptions.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/anthropic/AnthropicChatOptions.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/anthropic3/Anthropic3ChatOptions.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/cohere/BedrockCohereChatOptions.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/cohere/BedrockCohereEmbeddingOptions.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/jurassic2/BedrockAi21Jurassic2ChatOptions.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/llama/BedrockLlamaChatOptions.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/BedrockTitanChatOptions.java
  models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/BedrockTitanEmbeddingOptions.java
  models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/jurassic2/BedrockAi21Jurassic2ChatModelIT.java
  models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/MiniMaxChatOptions.java
  models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/MiniMaxEmbeddingOptions.java
  models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/MistralAiChatOptions.java
  models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/MistralAiEmbeddingOptions.java
  models/spring-ai-moonshot/src/main/java/org/springframework/ai/moonshot/MoonshotChatOptions.java
  models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaOptions.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatOptions.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiEmbeddingModel.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiImageModel.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/common/OpenAiApiConstants.java
  models/spring-ai-postgresml/src/main/java/org/springframework/ai/postgresml/PostgresMlEmbeddingOptions.java
  models/spring-ai-qianfan/src/main/java/org/springframework/ai/qianfan/QianFanChatOptions.java
  models/spring-ai-qianfan/src/main/java/org/springframework/ai/qianfan/QianFanEmbeddingOptions.java
  models/spring-ai-qianfan/src/main/java/org/springframework/ai/qianfan/QianFanImageOptions.java
  models/spring-ai-stability-ai/src/main/java/org/springframework/ai/stabilityai/api/StabilityAiImageOptions.java
  models/spring-ai-vertex-ai-gemini/src/main/java/org/springframework/ai/vertexai/gemini/VertexAiGeminiChatOptions.java
  models/spring-ai-vertex-ai-palm2/src/main/java/org/springframework/ai/vertexai/palm2/VertexAiPaLm2ChatOptions.java
  models/spring-ai-watsonx-ai/src/main/java/org/springframework/ai/watsonx/WatsonxAiChatOptions.java
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiChatOptions.java
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiEmbeddingOptions.java
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiImageOptions.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/observation/ChatModelObservationContext.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/observation/ChatModelRequestOptions.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/observation/DefaultChatModelObservationConvention.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/prompt/ChatOptions.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/prompt/ChatOptionsBuilder.java
  spring-ai-core/src/main/java/org/springframework/ai/embedding/observation/DefaultEmbeddingModelObservationConvention.java
  spring-ai-core/src/main/java/org/springframework/ai/embedding/observation/EmbeddingModelObservationContext.java
  spring-ai-core/src/main/java/org/springframework/ai/image/observation/DefaultImageModelObservationConvention.java
  spring-ai-core/src/main/java/org/springframework/ai/image/observation/ImageModelObservationContext.java
  spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallingOptionsBuilder.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/observation/ChatModelCompletionObservationFilterTests.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/observation/ChatModelMeterObservationHandlerTests.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/observation/ChatModelObservationContextTests.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/observation/ChatModelPromptContentObservationFilterTests.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/observation/ChatModelRequestOptionsTests.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/observation/DefaultChatModelObservationConventionTests.java
  spring-ai-core/src/test/java/org/springframework/ai/embedding/observation/DefaultEmbeddingModelObservationConventionTests.java
  spring-ai-core/src/test/java/org/springframework/ai/embedding/observation/EmbeddingModelMeterObservationHandlerTests.java
  spring-ai-core/src/test/java/org/springframework/ai/embedding/observation/EmbeddingModelObservationContextTests.java
  spring-ai-core/src/test/java/org/springframework/ai/image/observation/DefaultImageModelObservationConventionTests.java
  spring-ai-core/src/test/java/org/springframework/ai/image/observation/ImageModelObservationContextTests.java
  spring-ai-core/src/test/java/org/springframework/ai/image/observation/ImageModelPromptContentObservationFilterTests.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/mistralai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/upgrade-notes.adoc
  spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/zhipuai/ZhiPuAiPropertiesTests.java
Labels: model client, Observability, chat client

#1175 Add observability support for ChatClient
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/ChatClient.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/DefaultChatClientBuilder.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/RequestResponseAdvisor.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientInputContentObservationFilter.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationContext.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationConvention.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationDocumentation.java
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConvention.java
  spring-ai-core/src/main/java/org/springframework/ai/observation/conventions/AiOperationType.java
  spring-ai-core/src/main/java/org/springframework/ai/observation/conventions/AiProvider.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/ChatClientInputContentObservationFilterTests.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/ChatClientObservationContextTests.java
  spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConventionTests.java
  spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/chat/client/ChatClientAutoConfiguration.java
  spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/chat/client/ChatClientBuilderProperties.java
  spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/chat/client/ChatClientObservationAutoConfigurationTests.java
Labels: Observability

#1192 docs(onnx): add a note when the onnxruntime_gpu dependency is missing.
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/onnx.adoc
Labels: embedding, model client

#1223 Fix typos
  models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/api/AnthropicApi.java
  models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/api/MiniMaxApi.java
  models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/api/MistralAiApi.java
  models/spring-ai-moonshot/src/main/java/org/springframework/ai/moonshot/api/MoonshotApi.java
  models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaApi.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
  models/spring-ai-qianfan/src/main/java/org/springframework/ai/qianfan/api/QianFanApi.java
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiApi.java
Labels: code cleanup

#1217 Fix typos in openai-transcriptions.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/audio/transcriptions/openai-transcriptions.adoc
Labels: documentation

#1208 Remove unnecessary if statement in 'toolFunctionCall' test code from OpenAiApiToolFunctionCallIT
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/api/tool/OpenAiApiToolFunctionCallIT.java
Labels: testing
