Repository spring-projects/spring-ai, pull requests merged in 2024-09, with the labels that each got.

#1305 Fix problem with VectorStoreChatMemoryAdvisor using pgvector
  spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/VectorStoreChatMemoryAdvisor.java
  vector-stores/spring-ai-pgvector-store/src/test/java/org/springframework/ai/vectorstore/PgVectorStoreWithChatMemoryAdvisorIT.java
Labels: bug, advisors

#1317 Fix where previous Assistant Messages were not being added to the parts list
  models/spring-ai-vertex-ai-gemini/src/main/java/org/springframework/ai/vertexai/gemini/VertexAiGeminiChatModel.java
Labels: bug, model client, vertex

#1312 Fix cassandra starter
  spring-ai-bom/pom.xml
Labels: bug, vector store

#1315 Add spring-ai-spring-boot-docker-compose to BOM
  spring-ai-bom/pom.xml
Labels: bug, docker-compose
