Repository spring-projects/spring-ai, pull requests merged in 2025-10, with the labels that each got.

#4524 Fix JsonSchemaGenerator for method input parameters
  spring-ai-model/src/main/java/org/springframework/ai/util/json/schema/JsonSchemaGenerator.java
  spring-ai-model/src/test/java/org/springframework/ai/util/json/JsonSchemaGeneratorTests.java
Labels: mistral, for: backport-to-1.0.x

#4531 Upgrade MCP to 0.14.0 and mcp-annotations to 0.5.0
  mcp/mcp-annotations-spring/src/main/java/org/springframework/ai/mcp/annotation/spring/SyncMcpAnnotationProviders.java
  pom.xml
Labels: MCP

#4539 docs: Add Z.ai international site and glm-4.6 support
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiApi.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/zhipuai-chat.adoc
Labels: documentation, ZhiPu

#4532 Add MCP security ref docs
  spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-security.adoc
Labels: documentation

#4547 Correct `required` word
  models/spring-ai-google-genai/src/test/java/org/springframework/ai/google/genai/tool/GoogleGenAiPaymentTransactionIT.java
  models/spring-ai-vertex-ai-gemini/src/test/java/org/springframework/ai/vertexai/gemini/tool/VertexAiGeminiPaymentTransactionIT.java
Labels: code cleanup

#4541 docs: Deprecate and replace function-related options in chat models
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/dmr-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/google-genai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/groq-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/minimax-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/mistralai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/nvidia-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/vertexai-gemini-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/zhipuai-chat.adoc
Labels: documentation
