Repository spring-projects/spring-ai, pull requests merged in 2025-08, with the labels that each got.

#3985 test: Enhance test cases for `VectorStoreChatMemoryAdvisor` builder
  advisors/spring-ai-advisors-vector-store/src/test/java/org/springframework/ai/chat/client/advisor/vectorstore/VectorStoreChatMemoryAdvisorTests.java
Labels: testing

#3978 Lambda can be replaced with method reference
  models/spring-ai-transformers/src/main/java/org/springframework/ai/transformers/TransformersEmbeddingModel.java
  spring-ai-commons/src/main/java/org/springframework/ai/document/DefaultContentFormatter.java
  spring-ai-model/src/main/java/org/springframework/ai/model/ModelOptionsUtils.java
Labels: code cleanup

#3976 Use `Optional` to check null.
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java
Labels: code cleanup

#3980 Use `metadata` instead of `properties` on UserMessage.
  spring-ai-model/src/main/java/org/springframework/ai/chat/messages/UserMessage.java
Labels: improvement, for: backport-to-1.0.x

#3973 test: Enhance `AnthropicChatOptions` test coverage
  models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/AnthropicChatOptionsTests.java
Labels: testing

#3968 test: Enhance `MistralAiChatOptions` test coverage with comprehensive edge cases
  models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiChatOptionsTests.java
Labels: testing

#3959 test: Enhance `OpenAiChatOptions` test coverage
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/OpenAiChatOptionsTests.java
Labels: testing

#3943 test: Add comprehensive test coverage for `MariaDBFilterExpressionConverter`
  vector-stores/spring-ai-mariadb-store/src/test/java/org/springframework/ai/vectorstore/mariadb/MariaDBFilterExpressionConverterTests.java
Labels: testing

#3950 test: Add additional test coverage for `OpenSearchAiSearchFilterExpressionConverter`
  vector-stores/spring-ai-opensearch-store/src/test/java/org/springframework/ai/vectorstore/opensearch/OpenSearchAiSearchFilterExpressionConverterTest.java
Labels: testing

#3934 Bump postgresql JDBC driver from 42.7.5 to 42.7.7
  pom.xml
Labels: dependencies, for: backport-to-1.0.x

#3932 test: Add comprehensive test coverage for `PineconeFilterExpressionConverter`
  spring-ai-vector-store/src/test/java/org/springframework/ai/vectorstore/filter/converter/PineconeFilterExpressionConverterTests.java
Labels: testing

#3919 test: Add comprehensive test coverage for `MongoDBAtlasFilterExpressionConverter`
  vector-stores/spring-ai-mongodb-atlas-store/src/test/java/org/springframework/ai/vectorstore/mongodb/atlas/MongoDBAtlasFilterConverterTest.java
Labels: testing

#3916 test: Add comprehensive test coverage for `PgVectorFilterExpressionConverter`
  vector-stores/spring-ai-pgvector-store/src/test/java/org/springframework/ai/vectorstore/pgvector/PgVectorFilterExpressionConverterTests.java
Labels: testing

#3963 Improved documentation for the `call()` method in `chatclient.adoc`
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
Labels: documentation, for: backport-to-1.0.x

#4016 test: Add comprehensive test coverage for `PdfReaderRuntimeHints`
  document-readers/pdf-reader/src/test/java/org/springframework/ai/reader/pdf/aot/PdfReaderRuntimeHintsTests.java
Labels: testing

#4008 docs: Update ChromaDB configuration details for Chroma Cloud support
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/chroma.adoc
Labels: documentation, for: backport-to-1.0.x

#4014 test: Add comprehensive test coverage for `Ollama` runtime hints registration
  models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/aot/OllamaRuntimeHintsTests.java
Labels: testing

#4013 test: Add edge case tests for `VertexAI` `Gemini` runtime hints registration
  models/spring-ai-vertex-ai-gemini/src/test/java/org/springframework/ai/vertexai/gemini/aot/VertexAiGeminiRuntimeHintsTests.java
Labels: testing

#4028 test: Add comprehensive edge case and validation tests for runtime hints registration
  memory/repository/spring-ai-model-chat-memory-repository-jdbc/src/test/java/org/springframework/ai/chat/memory/repository/jdbc/aot/hint/JdbcChatMemoryRepositoryRuntimeHintsTest.java
  spring-ai-model/src/test/java/org/springframework/ai/aot/AiRuntimeHintsTests.java
  spring-ai-model/src/test/java/org/springframework/ai/aot/ToolRuntimeHintsTests.java
Labels: testing

#3917 doc: update chat-memory.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat-memory.adoc
Labels: documentation, for: backport-to-1.0.x

#3936 Fix typos in comments and improve documentation
  models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/AnthropicChatModel.java
  models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/client/AnthropicChatClientIT.java
  models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureOpenAiChatModelIT.java
  models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/BedrockConverseChatClientIT.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelObservationIT.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientIT.java
  spring-ai-test/README.md
Labels: code cleanup

#4034 test: Add comprehensive edge case and validation tests for core `Spring AI builders`
  spring-ai-commons/src/test/java/org/springframework/ai/document/DocumentBuilderTests.java
  spring-ai-model/src/test/java/org/springframework/ai/chat/prompt/PromptTemplateBuilderTests.java
  spring-ai-vector-store/src/test/java/org/springframework/ai/vectorstore/filter/FilterExpressionBuilderTests.java
Labels: testing

#3989 feat: Add `metadata` support to `PromptUserSpec` and `PromptSystemSpec` in ChatClient
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/ChatClient.java
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClientBuilder.java
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClientUtils.java
  spring-ai-client-chat/src/test/java/org/springframework/ai/chat/client/ChatClientTest.java
  spring-ai-client-chat/src/test/java/org/springframework/ai/chat/client/DefaultChatClientTests.java
Labels: chat client, improvement

#4041 test: Add comprehensive test coverage for `OCICohereChatOptions`, `AzureEmbeddingsOptions`, `WeaviateVectorStoreOptions` classes
  models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureEmbeddingsOptionsTests.java
  models/spring-ai-oci-genai/src/test/java/org/springframework/ai/oci/cohere/OCICohereChatOptionsTests.java
  vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreOptionsTests.java
Labels: testing

#4042 test: Add comprehensive test coverage for `AzureOpenAiChatOptions` and `PostgresMlEmbeddingOptions`
  models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureChatCompletionsOptionsTests.java
  models/spring-ai-postgresml/src/test/java/org/springframework/ai/postgresml/PostgresMlEmbeddingOptionsTests.java
Labels: testing

#3975 Keep the same pass check behavior for Evaluator
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/evaluation/FactCheckingEvaluator.java
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/evaluation/RelevancyEvaluator.java
Labels: improvement, for: backport-to-1.0.x

#3841 Use maven wrapper and batch-mode in GitHub Actions
  .github/workflows/continuous-inspection.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/documentation-upload.yml
  .github/workflows/pr-check.yml
Labels: improvement

#4072 Fix CI workflow: Use ../mvnw for assembly generation in spring-ai-docs
  .github/workflows/continuous-integration.yml
Labels: improvement

#4077 added new model names in anthropic doc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
Labels: documentation, anthropic, for: backport-to-1.0.x

#4064 Polish: Use `Optional` to check null, and avoid NPE
  spring-ai-model/src/main/java/org/springframework/ai/chat/model/StreamingChatModel.java
Labels: improvement, for: backport-to-1.0.x

#4063 Polish: Use `Optional` to check null, and avoid NPE.
  spring-ai-model/src/main/java/org/springframework/ai/embedding/observation/DefaultEmbeddingModelObservationConvention.java
Labels: improvement, for: backport-to-1.0.x

#4095 test: Add additional filter condition tests for `SimpleVectorStore`
  spring-ai-vector-store/src/test/java/org/springframework/ai/vectorstore/SimpleVectorStoreWithFilterTests.java
Labels: testing

#4094 Issue 4082 Fix ResourceAccessException retry for network connectivity errors
  spring-ai-retry/src/main/java/org/springframework/ai/retry/RetryUtils.java
Labels: retry, improvement, for: backport-to-1.0.x

#4135 Fix intermittent streaming response aggregation test failure
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientIT.java
Labels: testing

#4154 test: Enhance test coverage for `SyncMcpToolCallback` edge cases
  mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackTests.java
Labels: testing

#4153 fix: correctly handle merges when 'current' is null
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiStreamFunctionCallingHelper.java
Labels: bug

#4157 test: Enhance test coverage for `EmbeddingModelObservationContext`
  spring-ai-model/src/test/java/org/springframework/ai/embedding/observation/EmbeddingModelObservationContextTests.java
Labels: testing

#4086 Feat: add gpt 5 models and verbosity param
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatOptions.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/api/OpenAiApiIT.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Labels: improvement

#4152 chore(google genai): return the actual model version used for chat
  models/spring-ai-google-genai/src/main/java/org/springframework/ai/google/genai/GoogleGenAiChatModel.java
Labels: bug

#4165 test: Enhance test coverage for `MistralAiBindingsPropertiesProcessor`
  spring-ai-spring-cloud-bindings/src/test/java/org/springframework/ai/bindings/MistralAiBindingsPropertiesProcessorTests.java
Labels: testing

#4187 Bump io.swagger.core.v3:swagger-annotations from 2.2.25 to 2.2.30
  pom.xml
Labels: dependencies

#4253 Update docker services documentation
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/docker-compose.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/testcontainers.adoc
Labels: documentation

#4156 Fix reordering issue in AzureOpenAiChatModel (Fixes #4155)
  models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatModel.java
Labels: bug

#4104 chore: remove unnecessary null checks
  spring-ai-template-st/src/main/java/org/springframework/ai/template/st/StTemplateRenderer.java
Labels: code cleanup
