Repository spring-projects/spring-ai, pull requests merged in 2025-04, with the labels that each got.

#2608 docs: fix BakLLaVA model name spelling in multimodality documentation
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/multimodality.adoc
Labels: documentation, ollama

#2563 Fix: Duplicate example in Vector Databases documentation
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs.adoc
Labels: documentation, vector store

#2550 Update vectordbs doc,batching-strategy is remove
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/elasticsearch.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/neo4j.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/opensearch.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pgvector.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/qdrant.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/redis.adoc
Labels: documentation, vector store

#2624 update mcp-client-boot-starter-docs.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-client-boot-starter-docs.adoc
Labels: documentation, MCP

#2626 Fix typo in ETL pipeline document
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/etl-pipeline.adoc
Labels: documentation, ETL

#2665 fix typo in ToolCallingAutoConfigurationTests
  auto-configurations/models/tool/spring-ai-autoconfigure-model-tool/src/test/java/org/springframework/ai/model/tool/autoconfigure/ToolCallingAutoConfigurationTests.java
Labels: tool/function calling

#2661 Update `OpenAiApiToolFunctionCallIT` source
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/openai-chat-functions.adoc
Labels: documentation

#2654 feat(mcp): update WebFlux and WebMvc server transport providers with URL configuration
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpBackwardCompatibility.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfiguration.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerProperties.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/test/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfigurationBackwardCompatibilityIT.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/test/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfigurationIT.java
  mcp/common/src/main/java/org/springframework/ai/mcp/AsyncMcpToolCallbackProvider.java
  mcp/common/src/main/java/org/springframework/ai/mcp/McpToolUtils.java
  mcp/common/src/main/java/org/springframework/ai/mcp/SyncMcpToolCallbackProvider.java
  mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackProviderTests.java
  mcp/common/src/test/java/org/springframework/ai/mcp/ToolUtilsDeprecatedTests.java
  pom.xml
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
Labels: MCP

#2721 Add missing chat memory entries to BOM
  pom.xml
  spring-ai-bom/pom.xml
  spring-ai-spring-boot-starters/spring-ai-starter-model-chat-memory-cassandra/pom.xml
  spring-ai-spring-boot-starters/spring-ai-starter-model-chat-memory-neo4j/pom.xml
Labels: Chat Memory

#2719 Fix typo
  models/spring-ai-mistral-ai/src/test/resources/prompts/acme/system-qa.st
  models/spring-ai-openai/src/test/resources/prompts/acme/system-qa.st
  spring-ai-commons/src/main/java/org/springframework/ai/document/id/IdGenerator.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc
Labels: documentation

#2741 Update tools.adoc , change colon to semicolon
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Labels: documentation

#2790 Upgrade azure-open-ai-client to 1.0.0-beta.16
  models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/MergeUtils.java
  pom.xml
Labels: enhancement

#2852 Update dependencies and cleanup misc version management
  auto-configurations/models/chat/memory/spring-ai-autoconfigure-model-chat-memory-neo4j/pom.xml
  document-readers/jsoup-reader/pom.xml
  pom.xml
  spring-ai-client-chat/pom.xml
  spring-ai-model/pom.xml
  vector-stores/spring-ai-azure-cosmos-db-store/pom.xml
  vector-stores/spring-ai-gemfire-store/pom.xml
  vector-stores/spring-ai-mongodb-atlas-store/pom.xml
  vector-stores/spring-ai-neo4j-store/pom.xml
Labels: enhancement

#2854 chore: Fix typo in toolContext.
  spring-ai-model/src/main/java/org/springframework/ai/model/function/FunctionCallback.java
Labels: documentation

#2880 Update getting-started.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc
Labels: documentation

#2809 Update mongodb.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/mongodb.adoc
Labels: documentation

#1810 Docs don't show these as bullets because they are in a note block.
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/advisors.adoc
Labels: documentation

#2663 Switch CassandraContainer implementation
  auto-configurations/models/chat/memory/spring-ai-autoconfigure-model-chat-memory-cassandra/src/test/java/org/springframework/ai/model/chat/memory/cassandra/autoconfigure/CassandraChatMemoryAutoConfigurationIT.java
  auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-cassandra/src/test/java/org/springframework/ai/vectorstore/cassandra/autoconfigure/CassandraVectorStoreAutoConfigurationIT.java
  memory/spring-ai-model-chat-memory-cassandra/src/test/java/org/springframework/ai/chat/memory/cassandra/CassandraChatMemoryIT.java
  vector-stores/spring-ai-cassandra-store/src/test/java/org/springframework/ai/vectorstore/cassandra/CassandraRichSchemaVectorStoreIT.java
  vector-stores/spring-ai-cassandra-store/src/test/java/org/springframework/ai/vectorstore/cassandra/CassandraVectorStoreIT.java
  vector-stores/spring-ai-cassandra-store/src/test/java/org/springframework/ai/vectorstore/cassandra/CassandraVectorStoreObservationIT.java
Labels: cassandra

#2749 feat
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/retrieval-augmented-generation.adoc
Labels: documentation

#2689 Remove broken example applications from list
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
Labels: documentation

#2859 Rename ToolRegistration to ToolSpecification
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/test/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfigurationIT.java
  mcp/common/src/main/java/org/springframework/ai/mcp/McpToolUtils.java
  spring-ai-docs/src/main/antora/modules/ROOT/images/mcp/java-mcp-uml-classdiagram.svg
Labels: documentation

#2762 Update deprecated Media constructor usage in docs
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
Labels: documentation

#2842 Fix missing table name in exception message in CassandraVectorStore
  vector-stores/spring-ai-cassandra-store/src/main/java/org/springframework/ai/vectorstore/cassandra/CassandraVectorStore.java
Labels: vector store, cassandra

#2744 GH-2743: Correct erroneous content in documents
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/usage-handling.adoc
Labels: documentation

#2802 chore: Use stream flatmap when build toolcallbacks.
  mcp/common/src/main/java/org/springframework/ai/mcp/SyncMcpToolCallbackProvider.java
Labels: code cleanup, MCP

#2946 Add tests for McpToolUtils.getToolCallbacksFromSyncClients method
  mcp/common/src/test/java/org/springframework/ai/mcp/ToolUtilsTests.java
Labels: testing, MCP
