Repository spring-projects/spring-ai, pull requests merged in 2025-07, with the labels that each got.

#3695 Fix typos
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/McpToolCallbackAutoConfigurationTests.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpSseClientPropertiesTests.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/transcription/TranscriptionModelTests.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiRetryTests.java
  models/spring-ai-vertex-ai-gemini/src/test/java/org/springframework/ai/vertexai/gemini/tool/VertexAiGeminiPaymentTransactionMethodIT.java
  models/spring-ai-vertex-ai-gemini/src/test/java/org/springframework/ai/vertexai/gemini/tool/VertexAiGeminiPaymentTransactionToolsIT.java
  vector-stores/spring-ai-cassandra-store/src/test/java/org/springframework/ai/vectorstore/cassandra/WikiVectorStoreExample.java
Labels: code cleanup

#3677 Fix typo in token configuration documentation
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
Labels: documentation, for: backport-to-1.0.x

#3663 Refactor: Add null check, optimize string joining, and add JavaDocs
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
Labels: code cleanup, for: backport-to-1.0.x

#3705 improve schema initialization logic and update deprecated code for Milvus vectorstore
  vector-stores/spring-ai-milvus-store/src/main/java/org/springframework/ai/vectorstore/milvus/MilvusVectorStore.java
  vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/milvus/MilvusVectorStoreIT.java
Labels: code cleanup, for: backport-to-1.0.x

#3458 Use diamond operator where possible
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpStdioClientProperties.java
  auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-mongodb-atlas/src/main/java/org/springframework/ai/vectorstore/mongodb/autoconfigure/MongoDBAtlasVectorStoreAutoConfiguration.java
  document-readers/pdf-reader/src/main/java/org/springframework/ai/reader/pdf/layout/ForkPDFLayoutTextStripper.java
  document-readers/pdf-reader/src/main/java/org/springframework/ai/reader/pdf/layout/PDFLayoutTextStripperByArea.java
  models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/EventParsingTests.java
  models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/client/AnthropicChatClientIT.java
  models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/BedrockConverseChatClientIT.java
  models/spring-ai-huggingface/src/main/java/org/springframework/ai/huggingface/HuggingfaceChatModel.java
  models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiChatClientIT.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelTypeReferenceBeanOutputConverterIT.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiPaymentTransactionIT.java
  models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientIT.java
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java
  spring-ai-client-chat/src/test/java/org/springframework/ai/chat/client/ChatClientResponseEntityTests.java
  spring-ai-commons/src/main/java/org/springframework/ai/document/DefaultContentFormatter.java
  spring-ai-commons/src/main/java/org/springframework/ai/reader/JsonReader.java
  spring-ai-commons/src/test/java/org/springframework/ai/template/NoOpTemplateRendererTests.java
  spring-ai-model/src/main/java/org/springframework/ai/chat/model/MessageAggregator.java
  spring-ai-model/src/main/java/org/springframework/ai/model/EmbeddingUtils.java
  spring-ai-model/src/main/java/org/springframework/ai/model/ModelOptionsUtils.java
  spring-ai-template-st/src/test/java/org/springframework/ai/template/st/StTemplateRendererTests.java
  vector-stores/spring-ai-azure-cosmos-db-store/src/main/java/org/springframework/ai/vectorstore/cosmosdb/CosmosDBVectorStore.java
  vector-stores/spring-ai-azure-store/src/main/java/org/springframework/ai/vectorstore/azure/AzureVectorStore.java
  vector-stores/spring-ai-mongodb-atlas-store/src/test/java/org/springframework/ai/vectorstore/mongodb/atlas/MongoDBAtlasVectorStoreIT.java
  vector-stores/spring-ai-mongodb-atlas-store/src/test/java/org/springframework/ai/vectorstore/mongodb/atlas/MongoDbVectorStoreObservationIT.java
  vector-stores/spring-ai-pgvector-store/src/main/java/org/springframework/ai/vectorstore/pgvector/PgVectorStore.java
  vector-stores/spring-ai-pinecone-store/src/main/java/org/springframework/ai/vectorstore/pinecone/PineconeVectorStore.java
  vector-stores/spring-ai-qdrant-store/src/main/java/org/springframework/ai/vectorstore/qdrant/QdrantFilterExpressionConverter.java
  vector-stores/spring-ai-qdrant-store/src/main/java/org/springframework/ai/vectorstore/qdrant/QdrantValueFactory.java
Labels: code cleanup, for: backport-to-1.0.x

#3228 docs: replace CLA section with DCO (#3094)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#3013 Fix typos in chat client module
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/ChatClient.java
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClientBuilder.java
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/package-info.java
Labels: code cleanup, for: backport-to-1.0.x

#3755 Fix NPE in AnthropicApi StreamHelper
  models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/api/StreamHelper.java
  models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/api/StreamHelperTests.java
Labels: anthropic, for: backport-to-1.0.x

#3760 Improve the MCP document to stop referring to outdated DefaultMcpSession
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-overview.adoc
Labels: documentation, MCP, for: backport-to-1.0.x

#3781 Upgrade io.modelcontextprotocol 0.10.0 -> 0.11.0-SNAPSHOT
  mcp/common/src/test/java/org/springframework/ai/mcp/AsyncMcpToolCallbackTest.java
  mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackTests.java
  pom.xml
Labels: MCP

#3802 Fix exmaple code for "Streaming Responses"
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
Labels: documentation, for: backport-to-1.0.x

#3751 docs(mcp): add dynamic MCP client selection example
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-helpers.adoc
Labels: documentation, MCP, for: backport-to-1.0.x

#2774 fix method tool call throws same method name
  spring-ai-model/src/main/java/org/springframework/ai/tool/method/MethodToolCallbackProvider.java
  spring-ai-model/src/test/java/org/springframework/ai/tool/method/MethodToolCallbackProviderTest.java
Labels: bug, for: backport-to-1.0.x

#3844 Fix: Fix CI failures
  mcp/common/src/test/java/org/springframework/ai/mcp/AsyncMcpToolCallbackTest.java
  mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackTests.java
Labels: CI/CD

#3843 GH-3842: Optimize the Bedrock documentation to keep it synchronized with the code
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/bedrock-converse.adoc
Labels: documentation, Bedrock

#3883 Apply AsciiDoc style for `CONTRIBUTING.adoc`
  CONTRIBUTING.adoc
Labels: documentation, for: backport-to-1.0.x
