Repository spring-projects/spring-ai, pull requests merged in 2025-09, with the labels that each got.

#4278 docs: Update tools.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Labels: documentation, for: backport-to-1.0.x

#4288 remove redundant try-catch in JdbcChatMemoryRepository
  memory/repository/spring-ai-model-chat-memory-repository-jdbc/src/main/java/org/springframework/ai/chat/memory/repository/jdbc/JdbcChatMemoryRepository.java
Labels: improvement, for: backport-to-1.0.x

#4147 Add StreamableHttpHttpClientTransportAutoConfigurationTests
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client-httpclient/src/test/java/org/springframework/ai/mcp/client/autoconfigure/StreamableHttpHttpClientTransportAutoConfigurationTests.java
Labels: testing, MCP

#4313 test: Enhance test coverage for image model observations components
  spring-ai-model/src/test/java/org/springframework/ai/image/observation/DefaultImageModelObservationConventionTests.java
  spring-ai-model/src/test/java/org/springframework/ai/image/observation/ImageModelObservationContextTests.java
  spring-ai-model/src/test/java/org/springframework/ai/tool/function/FunctionToolCallbackTest.java
Labels: testing

#4327 Improve Mistral AI javadoc and update documentation links
  models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/api/MistralAiApi.java
  models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/api/MistralAiModerationApi.java
Labels: documentation, mistral, for: backport-to-1.0.x

#4387 docs(zhipu): fix zhipuai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/zhipuai-chat.adoc
Labels: documentation, ZhiPu

#4398 Fixes #4397 Updated Google GenAI Dependencies to the latest versions …
  models/spring-ai-google-genai/src/test/java/org/springframework/ai/google/genai/tool/GoogleGenAiChatModelToolCallingIT.java
  pom.xml
Labels: google genai

#4402 test: Add comprehensive test coverage for runtime hints and bindings processors
  models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/aot/AzureOpenAiRuntimeHintsTests.java
  models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/aot/MistralAiRuntimeHintsTests.java
  spring-ai-spring-cloud-bindings/src/test/java/org/springframework/ai/bindings/MistralAiBindingsPropertiesProcessorTests.java
Labels: testing

#4320 build: define version of plugin `maven-gpg-plugin`
  pom.xml
Labels: for: backport-to-1.0.x

#3856 Improve method param name in ChatClient.Builder.defaultAdvisors()
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/ChatClient.java
Labels: advisors, for: backport-to-1.0.x

#3446 fix: Replace the expired annotation
  models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/cohere/BedrockCohereEmbeddingModelIT.java
Labels: code cleanup

#4415 Update MCP dependencies
  pom.xml
Labels: MCP

#4437 [Fixes #4436] Fix Typo in the OCI GenAI Cohere Chat Documentation
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/oci-genai/cohere-chat.adoc
Labels: documentation, for: backport-to-1.0.x

#4456 test: Add robust null safety and configuration testing for Azure OpenAI embeddings and Google GenAI runtime hints
  models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureEmbeddingsOptionsTests.java
  models/spring-ai-google-genai/src/test/java/org/springframework/ai/google/genai/aot/GoogleGenAiRuntimeHintsTests.java
Labels: testing

#4467 test: Add missing operator and edge case tests for AzureAiSearchFilterExpressionConverter
  vector-stores/spring-ai-azure-store/src/test/java/org/springframework/ai/vectorstore/azure/AzureAiSearchFilterExpressionConverterTests.java
Labels: testing, azure
