Repository spring-projects/spring-ai, pull requests merged in 2025-05, with the labels that each got.

#2960 feat(mcp): Add configurable SSE endpoint support for MCP client transports
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/SseHttpClientTransportAutoConfiguration.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/SseWebFluxTransportAutoConfiguration.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpSseClientProperties.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/SseHttpClientTransportAutoConfigurationTests.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/SseWebFluxTransportAutoConfigurationTests.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpClientCommonPropertiesTests.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpSseClientPropertiesTests.java
Labels: MCP

#3015 Update chat-memory.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat-memory.adoc
Labels: documentation

#3024 Fix incorrect artifactId
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
Labels: documentation

#3009 Update dependencies for milvus stores
  pom.xml
Labels: milvus

#3056 Update neo4j.adoc - change `spring.ai.vectorstore.neo4j.dimensions` to `spring.ai.vectorstore.neo4j.embedding-dimension`
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/neo4j.adoc
Labels: neo4j

#3114 OpenAiImageModel support configure imagesPath
  auto-configurations/models/spring-ai-autoconfigure-model-openai/src/main/java/org/springframework/ai/model/openai/autoconfigure/OpenAiImageAutoConfiguration.java
  auto-configurations/models/spring-ai-autoconfigure-model-openai/src/main/java/org/springframework/ai/model/openai/autoconfigure/OpenAiImageProperties.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiImageApi.java
Labels: openai

#3105 Fix wrong artifactId in DeepSeek document
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc
Labels: documentation

#3119 Add EnabledIfEnvironmentVariable annotation to MariaDBStoreCustomNamesIT
  vector-stores/spring-ai-mariadb-store/src/test/java/org/springframework/ai/vectorstore/mariadb/MariaDBStoreCustomNamesIT.java
Labels: mariadb

#3123 added custom path in doc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
Labels: documentation

#3140 Updated docs for new OpenSearch vector-store properties
  auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-opensearch/src/main/java/org/springframework/ai/vectorstore/opensearch/autoconfigure/OpenSearchVectorStoreProperties.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/opensearch.adoc
Labels: documentation

#3142 Simplify description of artifact and property name changes in repositorires
  spring-ai-docs/src/main/antora/modules/ROOT/pages/upgrade-notes.adoc
Labels: documentation

#3162 Docs: Fix typo in openai-moderation.doc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/moderation/openai-moderation.adoc
Labels: documentation

#3165 fix: OpenAiApi comment.
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
Labels: documentation

#3161 Documentation of the Mistral Moderation model
  spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/moderation/mistral-ai-moderation.adoc
Labels: documentation, mistral

#3171 [Doc] fix doc error
  spring-ai-docs/src/main/antora/modules/ROOT/pages/upgrade-notes.adoc
Labels: documentation

#3173 Fix qdrant vector store value factory
  vector-stores/spring-ai-qdrant-store/src/main/java/org/springframework/ai/vectorstore/qdrant/QdrantValueFactory.java
  vector-stores/spring-ai-qdrant-store/src/test/java/org/springframework/ai/vectorstore/qdrant/QdrantVectorStoreIT.java
Labels: qdrant

#3198 Polish dependencies
  memory/repository/spring-ai-model-chat-memory-repository-jdbc/pom.xml
Labels: Chat Memory, code cleanup

#3214 refactor: update dependencies to use spring-ai-model and spring-ai-commons
  document-readers/jsoup-reader/pom.xml
  document-readers/markdown-reader/pom.xml
  document-readers/pdf-reader/pom.xml
  document-readers/tika-reader/pom.xml
  mcp/common/pom.xml
  memory/repository/spring-ai-model-chat-memory-repository-cassandra/pom.xml
  memory/repository/spring-ai-model-chat-memory-repository-neo4j/pom.xml
  models/spring-ai-anthropic/pom.xml
  models/spring-ai-azure-openai/pom.xml
  models/spring-ai-bedrock-converse/pom.xml
  models/spring-ai-bedrock/pom.xml
  models/spring-ai-deepseek/pom.xml
  models/spring-ai-huggingface/pom.xml
  models/spring-ai-minimax/pom.xml
  models/spring-ai-mistral-ai/pom.xml
  models/spring-ai-oci-genai/pom.xml
  models/spring-ai-ollama/pom.xml
  models/spring-ai-openai/pom.xml
  models/spring-ai-postgresml/pom.xml
  models/spring-ai-stability-ai/pom.xml
  models/spring-ai-transformers/pom.xml
  models/spring-ai-vertex-ai-embedding/pom.xml
  models/spring-ai-vertex-ai-gemini/pom.xml
  models/spring-ai-zhipuai/pom.xml
  spring-ai-retry/pom.xml
Labels: refactoring

#3218 Change log level from DEBUG to INFO for ObservationHandlers
  spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/observation/ChatClientPromptContentObservationHandler.java
  spring-ai-client-chat/src/test/java/org/springframework/ai/chat/client/observation/ChatClientPromptContentObservationHandlerTests.java
  spring-ai-model/src/main/java/org/springframework/ai/chat/observation/ChatModelCompletionObservationHandler.java
  spring-ai-model/src/main/java/org/springframework/ai/chat/observation/ChatModelPromptContentObservationHandler.java
  spring-ai-model/src/main/java/org/springframework/ai/image/observation/ImageModelPromptContentObservationHandler.java
  spring-ai-model/src/test/java/org/springframework/ai/chat/observation/ChatModelCompletionObservationHandlerTests.java
  spring-ai-model/src/test/java/org/springframework/ai/chat/observation/ChatModelPromptContentObservationHandlerTests.java
  spring-ai-model/src/test/java/org/springframework/ai/image/observation/ImageModelPromptContentObservationHandlerTests.java
  spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/observation/VectorStoreQueryResponseObservationHandler.java
  spring-ai-vector-store/src/test/java/org/springframework/ai/vectorstore/observation/VectorStoreQueryResponseObservationHandlerTests.java
Labels: bug, Observability

#3224 feat(mcp): Add request timeout configuration for MCP server
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfiguration.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerProperties.java
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/test/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfigurationIT.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
Labels: MCP

#3226 docs: Document the MCP ToolContext support
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
Labels: MCP

#3231 docs: reorganize tool calling documentation and add observability
  spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Labels: documentation, tool/function calling

#3244 MCP ToolCallbackProvider autoconfig should use concrete class
  auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/McpToolCallbackAutoConfiguration.java
Labels: MCP

#3247 add effective agents section
  spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/effective-agents.adoc
Labels: documentation

#3283 Fix datasource connection leak when using the JdbcChatMemoryRepository
  memory/repository/spring-ai-model-chat-memory-repository-jdbc/src/main/java/org/springframework/ai/chat/memory/repository/jdbc/JdbcChatMemoryRepositoryDialect.java
Labels: backport-to-1.0.x

#3275 Fix incorrect external link formatting in effective-agents.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/effective-agents.adoc
Labels: documentation, backport-to-1.0.x

#3279 Update mcp-server-boot-starter-docs.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
Labels: documentation, backport-to-1.0.x

#3292 Fix tools docs
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Labels: documentation

#3335 docs: update custom API key example using OpenAiChatModel.builder()
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Labels: documentation, backport-to-1.0.x

#3328 Fix awesome-spring-ai link to official repository
  README.md
  spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc
Labels: documentation, backport-to-1.0.x

#3325 Add metadata support for vector store types
  spring-ai-vector-store/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: vector store, backport-to-1.0.x

#3322 Fix links in documentation to `Media.java`
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/mistralai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Labels: documentation, backport-to-1.0.x

#3390 Fix CustomerTools example to use existing methods
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Labels: bug, documentation, for: backport-to-1.0.x

#3351 feat(anthropic): add support for claude-opus-4 and claude-sonnet-4
  models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/api/AnthropicApi.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
Labels: anthropic, for: backport-to-1.0.x

#3396 Avoid looping through all the page tree if there is no destination page
  document-readers/pdf-reader/src/main/java/org/springframework/ai/reader/pdf/config/ParagraphManager.java
Labels: bug, document-reader, for: backport-to-1.0.x

#3399 docs: add description of embedding-field-name property in elasticsearch.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/elasticsearch.adoc
Labels: documentation, for: backport-to-1.0.x
