Repository spring-projects/spring-ai, pull requests merged in 2025-06, with the labels that each got.

#3413 docs(bedrock-converse): fix MIME types and standardize formatting
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/bedrock-converse.adoc
Labels: documentation, for: backport-to-1.0.x

#3408 docs:Revise the documents of deepseek and minimax-chat
  models/spring-ai-deepseek/README.md
  models/spring-ai-deepseek/src/main/java/org/springframework/ai/deepseek/DeepSeekChatOptions.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/minimax-chat.adoc
Labels: documentation, for: backport-to-1.0.x

#3431 fix: correct ToolDefinition.builder() usage in docs
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Labels: documentation, for: backport-to-1.0.x

#3435 Fixed the missing properties in the AutoConfiguration of ChromaVectorStore
  auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-chroma/src/main/java/org/springframework/ai/vectorstore/chroma/autoconfigure/ChromaVectorStoreAutoConfiguration.java
Labels: bug

#3411 feat(openai): for tts and chat completions update supported voices enums
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiAudioApi.java
Labels: audio, for: backport-to-1.0.x

#3445 docs: update huggingface doc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/huggingface.adoc
Labels: documentation, for: backport-to-1.0.x

#3477 correct @formatter:onn to @formatter:on
  auto-configurations/models/spring-ai-autoconfigure-model-azure-openai/src/test/java/org/springframework/ai/model/azure/openai/autoconfigure/tool/FunctionCallWithFunctionBeanIT.java
  auto-configurations/models/spring-ai-autoconfigure-model-azure-openai/src/test/java/org/springframework/ai/model/azure/openai/autoconfigure/tool/FunctionCallWithFunctionWrapperIT.java
  auto-configurations/models/spring-ai-autoconfigure-model-azure-openai/src/test/java/org/springframework/ai/model/azure/openai/autoconfigure/tool/FunctionCallWithPromptFunctionIT.java
  models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/api/MistralAiModerationApi.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiImageApi.java
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiModerationApi.java
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiImageApi.java
Labels: testing, code cleanup

#3507 refactor(spring-ai-model): improve parameter name in ChatGenerationMetadata
  spring-ai-model/src/main/java/org/springframework/ai/chat/metadata/ChatGenerationMetadata.java
Labels: code cleanup

#3447 docs(web): fix broken links to ChatOptions and ChatOptions#builder()
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/dmr-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/groq-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/minimax-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/mistralai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/nvidia-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/perplexity-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/vertexai-gemini-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/zhipuai-chat.adoc
Labels: documentation, for: backport-to-1.0.x

#3531 Update zhipuai-chat.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/zhipuai-chat.adoc
Labels: documentation, for: backport-to-1.0.x

#3552 Update advisors.adoc
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/advisors.adoc
Labels: documentation

#3539 fix: failed to generate `spring.ai.tools.observations` config metadata
  auto-configurations/models/tool/spring-ai-autoconfigure-model-tool/src/main/java/org/springframework/ai/model/tool/autoconfigure/ToolCallingProperties.java
Labels: bug, tool/function calling, Observability, for: backport-to-1.0.x

#3575 Fix exception in `OpenAiAudioTranscriptionResponseMetadata.toString`
  models/spring-ai-openai/src/main/java/org/springframework/ai/openai/metadata/audio/OpenAiAudioTranscriptionResponseMetadata.java
Labels: bug, for: backport-to-1.0.x

#3583 docs: fix broken link to `ChatModel`
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatmodel.adoc
Labels: documentation, for: backport-to-1.0.x

#3582 chore: Fix order of getter and setter methods in `WeaviateVectorStoreProperties`
  auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-weaviate/src/main/java/org/springframework/ai/vectorstore/weaviate/autoconfigure/WeaviateVectorStoreProperties.java
Labels: code cleanup

#3574 Remove unused `messageHistory`
  spring-ai-model/src/main/java/org/springframework/ai/model/tool/DefaultToolCallingManager.java
Labels: code cleanup, for: backport-to-1.0.x

#3468 Update tools.adoc About toolDefinition parameter transfer error
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Labels: documentation

#3610 fix(elevenlabs): correct autoconfiguration class name and add ElevenLabs speech doc link
  auto-configurations/models/spring-ai-autoconfigure-model-elevenlabs/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc
Labels: for: backport-to-1.0.x

#3615 chore: Remove unnecessary environment variable validation in `QdrantVectorStoreIT`
  vector-stores/spring-ai-qdrant-store/src/test/java/org/springframework/ai/vectorstore/qdrant/QdrantVectorStoreIT.java
Labels: code cleanup, for: backport-to-1.0.x

#3621 Remove hardcoded topK in BedrockConverseProxyChatProperties
  auto-configurations/models/spring-ai-autoconfigure-model-bedrock-ai/src/main/java/org/springframework/ai/model/bedrock/converse/autoconfigure/BedrockConverseProxyChatProperties.java
Labels: Bedrock, code cleanup, for: backport-to-1.0.x

#3634 chore: Remove useless proerties tags
  models/spring-ai-openai/pom.xml
Labels: code cleanup

#3638 docs: correct `SimpleLoggerAdvisor` documentation
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
Labels: documentation, for: backport-to-1.0.x

#3652 fix: Correct naming inconsistencies in Mistral package
  models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/MistralAiChatModel.java
  models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/moderation/MistralAiModerationModel.java
  models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiChatModelObservationIT.java
  models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiEmbeddingModelObservationIT.java
Labels: code cleanup, for: backport-to-1.0.x

#3645 Fix incorrect ollama autoconfiguration changes
  auto-configurations/models/spring-ai-autoconfigure-model-ollama/pom.xml
  auto-configurations/models/spring-ai-autoconfigure-model-ollama/src/main/java/org/springframework/ai/model/ollama/autoconfigure/OllamaApiAutoConfiguration.java
  auto-configurations/models/spring-ai-autoconfigure-model-ollama/src/main/java/org/springframework/ai/model/ollama/autoconfigure/OllamaChatAutoConfiguration.java
  models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaEmbeddingModelObservationIT.java
  spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/ollama/OllamaAutoConfiguration.java
Labels: bug, for: backport-to-1.0.x

#3585 Make the `meta field prefix` configurable in Weaviate vector store properties
  auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-weaviate/src/main/java/org/springframework/ai/vectorstore/weaviate/autoconfigure/WeaviateVectorStoreAutoConfiguration.java
  auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-weaviate/src/main/java/org/springframework/ai/vectorstore/weaviate/autoconfigure/WeaviateVectorStoreProperties.java
  auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-weaviate/src/test/java/org/springframework/ai/vectorstore/weaviate/autoconfigure/WeaviateVectorStoreAutoConfigurationIT.java
  spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/weaviate.adoc
  vector-stores/spring-ai-weaviate-store/src/main/java/org/springframework/ai/vectorstore/weaviate/WeaviateFilterExpressionConverter.java
  vector-stores/spring-ai-weaviate-store/src/main/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStore.java
  vector-stores/spring-ai-weaviate-store/src/main/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreOptions.java
  vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreBuilderTests.java
  vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreIT.java
  vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreOptionsTests.java
Labels: vector store, weaviate

#3613 Remove `@Nullable` from VectorStore similaritySearch
  spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/VectorStore.java
  spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/observation/AbstractObservationVectorStore.java
  vector-stores/spring-ai-azure-cosmos-db-store/src/main/java/org/springframework/ai/vectorstore/cosmosdb/CosmosDBVectorStore.java
  vector-stores/spring-ai-chroma-store/src/main/java/org/springframework/ai/chroma/vectorstore/ChromaVectorStore.java
  vector-stores/spring-ai-gemfire-store/src/main/java/org/springframework/ai/vectorstore/gemfire/GemFireVectorStore.java
Labels: vector store, for: backport-to-1.0.x

#3668 fix: ZhiPuAiEmbedding supports custom dimensions
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiEmbeddingOptions.java
  models/spring-ai-zhipuai/src/test/java/org/springframework/ai/zhipuai/embedding/EmbeddingIT.java
Labels: ZhiPu, for: backport-to-1.0.x

#3669 fix: remove unused options from ZhiPu model
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiChatModel.java
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiChatOptions.java
  models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiApi.java
Labels: ZhiPu, for: backport-to-1.0.x

#3656 chore: fix `SimpleApiKey` assert message
  spring-ai-model/src/main/java/org/springframework/ai/model/SimpleApiKey.java
Labels: code cleanup, for: backport-to-1.0.x

#3687 Validate documents for text/media check when adding to vector store
  spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/observation/AbstractObservationVectorStore.java
  spring-ai-vector-store/src/test/java/org/springframework/ai/vectorstore/SimpleVectorStoreTests.java
  vector-stores/spring-ai-qdrant-store/src/test/java/org/springframework/ai/vectorstore/qdrant/QdrantVectorStoreIT.java
Labels: vector store, for: backport-to-1.0.x
